# Generated by Django 4.2.28 on 2026-02-18 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名')),
                ('icon', models.CharField(default='book', max_length=50, verbose_name='图标标识')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('question_count', models.IntegerField(default=0, verbose_name='题目数')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='子分类名')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='questions.category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '子分类',
                'verbose_name_plural': '子分类',
                'ordering': ['sort_order'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='题目标题')),
                ('brief_answer', models.TextField(blank=True, default='', verbose_name='回答话术')),
                ('detailed_answer', models.TextField(blank=True, default='', verbose_name='问题详解')),
                ('key_points', models.JSONField(blank=True, default=list, verbose_name='关键要点')),
                ('difficulty', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='难度')),
                ('source_url', models.URLField(blank=True, default='', verbose_name='来源链接')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.category', verbose_name='分类')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.subcategory', verbose_name='子分类')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'ordering': ['category', 'sub_category', 'id'],
            },
        ),
    ]
