# Generated by Django 4.2.28 on 2026-02-18 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型显示名')),
                ('provider', models.CharField(default='compshare', max_length=50, verbose_name='供应商')),
                ('api_key', models.CharField(max_length=200, verbose_name='API Key')),
                ('base_url', models.URLField(default='https://api.modelverse.cn/v1/', verbose_name='API Base URL')),
                ('model_name', models.CharField(default='deepseek-ai/DeepSeek-R1', help_text='如 deepseek-ai/DeepSeek-R1', max_length=200, verbose_name='模型标识')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
            ],
            options={
                'verbose_name': 'AI 模型配置',
                'verbose_name_plural': 'AI 模型配置',
            },
        ),
        migrations.CreateModel(
            name='AnswerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(verbose_name='用户回答')),
                ('ai_analysis', models.TextField(blank=True, default='', verbose_name='AI 分析')),
                ('ai_score', models.IntegerField(default=0, verbose_name='AI 评分')),
                ('ai_highlights', models.JSONField(blank=True, default=list, verbose_name='答对的点')),
                ('ai_missing_points', models.JSONField(blank=True, default=list, verbose_name='遗漏的点')),
                ('ai_suggestion', models.TextField(blank=True, default='', verbose_name='改进建议')),
                ('ai_improved_answer', models.TextField(blank=True, default='', verbose_name='AI 改进版答案')),
                ('ai_model_name', models.CharField(blank=True, default='', max_length=100, verbose_name='AI 模型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_records', to='questions.question', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_records', to='users.baguuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '答题记录',
                'verbose_name_plural': '答题记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
