# Generated by Django 4.2.28 on 2026-02-18 23:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('users', '0001_initial'),
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerrecord',
            name='ai_junior_comment',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='初级面试官评语'),
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='ai_junior_score',
            field=models.IntegerField(default=0, verbose_name='初级面试官评分'),
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='ai_mid_comment',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='中级面试官评语'),
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='ai_mid_score',
            field=models.IntegerField(default=0, verbose_name='中级面试官评分'),
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='ai_senior_comment',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='高级面试官评语'),
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='ai_senior_score',
            field=models.IntegerField(default=0, verbose_name='高级面试官评分'),
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='corrected_answer',
            field=models.TextField(blank=True, default='', verbose_name='纠错后回答'),
        ),
        migrations.CreateModel(
            name='FollowUpQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_question', models.TextField(verbose_name='用户追问')),
                ('ai_response', models.TextField(verbose_name='AI 回答')),
                ('ai_model_name', models.CharField(blank=True, default='', max_length=100, verbose_name='AI 模型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('answer_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='practice.answerrecord', verbose_name='答题记录')),
            ],
            options={
                'verbose_name': '追问记录',
                'verbose_name_plural': '追问记录',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_answer', models.TextField(verbose_name='用户回答')),
                ('composite_score', models.FloatField(default=0.0, verbose_name='综合评分')),
                ('model_count', models.IntegerField(default=0, verbose_name='模型数量')),
                ('completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_rounds', to='questions.question', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_rounds', to='users.baguuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '评估轮次',
                'verbose_name_plural': '评估轮次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_records', to='practice.evaluationround', verbose_name='评估轮次'),
        ),
    ]
