# Generated by Django 4.2.28 on 2026-02-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_answerrecord_ai_junior_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiRoleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_key', models.CharField(help_text='如 kind_architect / passionate_engineer / female_reviewer', max_length=50, unique=True, verbose_name='角色标识')),
                ('name', models.CharField(max_length=100, verbose_name='角色名称')),
                ('role_prompt', models.TextField(default='', help_text='该角色的评分风格、关注点与输出要求', verbose_name='角色提示词')),
                ('tts_model', models.CharField(default='IndexTeam/IndexTTS-2', help_text='参考 ModelVerse 文档，如 IndexTeam/IndexTTS-2', max_length=100, verbose_name='TTS 模型')),
                ('voice', models.CharField(blank=True, default='jack_cheng', help_text='ModelVerse /v1/audio/speech 的 voice 字段值（内置名或 uspeech:xxxx）', max_length=120, verbose_name='TTS 音色')),
                ('voice_label', models.CharField(blank=True, default='', max_length=100, verbose_name='音色说明')),
                ('weight', models.IntegerField(default=33, verbose_name='评分权重(%)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': 'AI 角色配置',
                'verbose_name_plural': 'AI 角色配置',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='ai_role_scores',
            field=models.JSONField(blank=True, default=list, verbose_name='角色评分详情'),
        ),
    ]
