# Generated by Codex on 2026-02-19

from django.db import migrations


def seed_roles(apps, schema_editor):
    AiRoleConfig = apps.get_model('practice', 'AiRoleConfig')

    defaults = [
        {
            'role_key': 'kind_architect_p7',
            'name': '和蔼型 P7 架构师',
            'role_prompt': '你是有多年一线经验的 P7 架构师，关注回答是否体现真实工程落地能力、架构权衡、稳定性和性能思维。你说话和蔼、鼓励式反馈，但会明确指出关键缺口。',
            'tts_model': 'IndexTeam/IndexTTS-2',
            'voice': 'stephen_chow',
            'voice_label': '沉稳架构师男声',
            'weight': 40,
            'sort_order': 1,
            'is_enabled': True,
        },
        {
            'role_key': 'passionate_engineer',
            'name': '技术热情型工程师',
            'role_prompt': '你是刚进入团队但技术底层扎实的工程师，关注基础概念、术语准确性、代码实践意识和学习热情。反馈直接、积极，指出可快速改进的点。',
            'tts_model': 'IndexTeam/IndexTTS-2',
            'voice': 'jack_cheng',
            'voice_label': '热情技术男声',
            'weight': 30,
            'sort_order': 2,
            'is_enabled': True,
        },
        {
            'role_key': 'female_reviewer',
            'name': '细致型女面试官',
            'role_prompt': '你是一位技术扎实、表达清晰的女面试官，关注回答的结构化表达、边界条件、可维护性与团队协作意识。反馈细致专业，兼顾准确性与沟通质量。',
            'tts_model': 'IndexTeam/IndexTTS-2',
            'voice': 'crystla_liu',
            'voice_label': '清晰女声',
            'weight': 30,
            'sort_order': 3,
            'is_enabled': True,
        },
    ]

    for role in defaults:
        AiRoleConfig.objects.update_or_create(
            role_key=role['role_key'],
            defaults=role,
        )


def unseed_roles(apps, schema_editor):
    AiRoleConfig = apps.get_model('practice', 'AiRoleConfig')
    AiRoleConfig.objects.filter(
        role_key__in=['kind_architect_p7', 'passionate_engineer', 'female_reviewer']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_airoleconfig_answerrecord_ai_role_scores'),
    ]

    operations = [
        migrations.RunPython(seed_roles, unseed_roles),
    ]
