# Generated by Django 4.2.28 on 2026-02-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_seed_default_ai_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='airoleconfig',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='medium', help_text='该角色对应的面试难度', max_length=20, verbose_name='难度等级'),
        ),
    ]
