# Generated by Codex on 2026-02-19

from django.db import migrations


def set_difficulty_levels(apps, schema_editor):
    AiRoleConfig = apps.get_model('practice', 'AiRoleConfig')
    mapping = {
        'passionate_engineer': 'easy',
        'female_reviewer': 'medium',
        'kind_architect_p7': 'hard',
    }
    for role_key, level in mapping.items():
        AiRoleConfig.objects.filter(role_key=role_key).update(difficulty_level=level)


def revert_difficulty_levels(apps, schema_editor):
    AiRoleConfig = apps.get_model('practice', 'AiRoleConfig')
    AiRoleConfig.objects.filter(
        role_key__in=['passionate_engineer', 'female_reviewer', 'kind_architect_p7']
    ).update(difficulty_level='medium')


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_airoleconfig_difficulty_level'),
    ]

    operations = [
        migrations.RunPython(set_difficulty_levels, revert_difficulty_levels),
    ]
