# Generated by Django 4.2.28 on 2026-02-18 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaguUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('nickname', models.CharField(blank=True, default='', max_length=50, verbose_name='昵称')),
                ('role', models.IntegerField(choices=[(0, '普通用户'), (1, '管理员')], default=0, verbose_name='角色')),
                ('total_answers', models.IntegerField(default=0, verbose_name='总答题数')),
                ('avg_score', models.FloatField(default=0.0, verbose_name='平均分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_scores', models.JSONField(blank=True, default=dict, help_text='{"Redis": 85, "并发编程": 60}', verbose_name='分类评分')),
                ('strengths', models.JSONField(blank=True, default=list, verbose_name='优势领域')),
                ('weaknesses', models.JSONField(blank=True, default=list, verbose_name='薄弱领域')),
                ('suggestions', models.JSONField(blank=True, default=list, verbose_name='学习建议')),
                ('overall_level', models.CharField(choices=[('beginner', '入门'), ('intermediate', '熟练'), ('advanced', '精通')], default='beginner', max_length=20, verbose_name='综合水平')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.baguuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户画像',
                'verbose_name_plural': '用户画像',
            },
        ),
    ]
